### ISSUE TITLE
Using wildcard matching causes a NPE

### ISSUE THREAD

**Issue by kylefowler** [RadiusNetworks/android-ibeacon-service#1]
When trying to specify matching on wildcard (like the sample in the github readme), the code will crash with a NPE because the normalizing method for the proximity uuid expects the string to be not null.
![screen shot 2013-10-07 at 11 13 07 am](https://f.cloud.github.com/assets/818067/1282925/957f02bc-2f7c-11e3-97b8-d4d2753c66ae.png)

**Comment by davidgyoung** [comment]
Thanks!  This is fixed in https://github.com/RadiusNetworks/android-ibeacon-service/commit/6e8522ffc0aec43512780b228a31edb742596911
