### ISSUE TITLE
Failed to set background mode

### ISSUE THREAD

**Issue by pablocoberly** [RadiusNetworks/android-ibeacon-service#11]
When binding to the iBeaconManager from my activity in background mode, logcat tells me that the IBeaconManager is not bound to the service. However, the ibeaconservice does get created and is subsequently bound.

12-17 16:20:47.092: E/IBeaconManager(27664): Failed to set background mode
12-17 16:20:47.092: E/IBeaconManager(27664): android.os.RemoteException: The IBeaconManager is not bound to the service.  Call iBeaconManager.bind(IBeaconConsumer consumer) and wait for a callback to onIBeaconServiceConnect()
12-17 16:20:47.092: E/IBeaconManager(27664):    at com.radiusnetworks.ibeacon.IBeaconManager.setScanPeriods(IBeaconManager.java:382)
12-17 16:20:47.092: E/IBeaconManager(27664):    at com.radiusnetworks.ibeacon.IBeaconManager.setBackgroundMode(IBeaconManager.java:266)
12-17 16:20:47.092: E/IBeaconManager(27664):    at com.radiusnetworks.ibeacon.IBeaconManager.bind(IBeaconManager.java:205)

**Comment by davidgyoung** [comment]
Thanks for the report.  This is a bug in the code that causes the stack trace to be put in the log the first time anything binds to the IBeaconManager.  Other than being ugly, the stack track is harmless and can be ignored.  It will be fixed in the next binary release.

**Comment by davidgyoung** [comment]
Fixed in binary release 0.7.2

**Comment by AkshayLuthra** [comment]
From where I can get the pull for "Fixed in binary release 0.7.2". I am having the same issue as @pablocoberly . I took the latest code from the Git but still having the same issue.Could you please give the link for the latest fixes.

**Comment by pablocoberly** [comment]
Doesn't look like it's available anymore. See http://developer.radiusnetworks.com/2014/07/14/a-note-from-the-ceo.html
