### ISSUE TITLE
Region equals() method bug

### ISSUE THREAD

**Issue by rwozniak** [RadiusNetworks/android-ibeacon-service#12]
In the method of class Region:

```
        public boolean equals(Object other) {
                 if (other instanceof Region) {
                        return ((Region)other).uniqueId == this.uniqueId;                         
                 }
                 return false;
        }
```

uniqueIds (which are Strings) are compared using '==' instead of .equals().
This will cause problems in collections (eg. removing from Map).

**Comment by davidgyoung** [comment]
Great catch, thanks!  Fixed in e18f35ad056f544d9fc25cde1dfb78520180ceb4 and binary release 0.7.2
