### ISSUE TITLE
UUID for Android client?

### ISSUE THREAD

**Issue by javaguy44** [RadiusNetworks/android-ibeacon-service#13]
Hi David,

I really like what you have done w/ the Android library, but one question; I’m not getting the UUID from the transmitting device when doing a wildcard search etc.

Even if I’m doing a wildcard search, doesn’t it make sense to include the UUID of whatever beacons are found like you mentioned in your post e.g.
http://developer.radiusnetworks.com/2013/10/01/reverse-engineering-the-ibeacon-profile.html

Thanks

**Comment by davidgyoung** [comment]
Hi, Javaguy.  When you talk about not getting the uuid, are you talking
about the "monitoring" API?  There is also a ranging API which does give
you all the identifiers of each iBeacon seen.  This is what you want to use.

It may seem funny that the monitoring API does not supply identifiers for
the iBeacons detected, but this is how the equivalent iOS APIs work, and I
modeled the Android API off of those in iOS.  This way, cross-platform apps
are easier.

Cheers,
David
