### ISSUE TITLE
Background mode is not working properly

### ISSUE THREAD

**Issue by ramakrishnakalla** [RadiusNetworks/android-ibeacon-service#15]
When I press back button in Main Activity the iBeaconService is unbinding automatically. I didn't unbind the service in onDestroy too,
1. Then how does this automatic unbinding happen?
Due to this, I am not able to detect beacons when app runs in background mode.
2. How do i monitor the beacons in background mode?
Also observed in logcat the message
 "has leaked ServiceConnection com.radiusnetworks.ibeacon.IBeaconManager$1@42a28f18 that was originally bound here".

**Comment by davidgyoung** [comment]
See answer here:  http://stackoverflow.com/questions/21006764/setbackground-is-not-working-properly-in-ibeacon-service
