### ISSUE TITLE
Android SDK - setForegroundScanPeriod in IBeaconManager doesn't work

### ISSUE THREAD

**Issue by rnevet** [RadiusNetworks/android-ibeacon-service#17]
setForegroundScanPeriod doesn't work, looking at the code line 138 it sets the wrong internal parameter "foregroundBetweenScanPeriod" instead of "foregroundScanPeriod".

**Comment by davidgyoung** [comment]
Nice catch, thank you!

Fixed in bfd2d7d.

This will be available in the next binary release by the end of the week.  Let me know if you need something sooner.

**Comment by rnevet** [comment]
I modified a local version.

Just a comment,
I would document that call the set*ScanPeriod functions won't take effect if scanning is in progress and it's necessary to call setScanPeriods() to apply the changes if you already started scanning.

Or another options is to check if the service interface is there and then call the setScanPeriods() - less flexible but an easier use case.

**Comment by davidgyoung** [comment]
Good point.  I don't want to make the call to setScanPeriods() automatic, because it becomes a remote call that throws a RemoteException.  The real intention is that this is configured up front and not at run time.  (Although nothing stops you from doing that if you really want.)

How about this for documentation?

```
/**
 * Sets the duration in milliseconds of each Bluetooth LE scan cycle to look for iBeacons when no
 * ranging/monitoring clients are in the foreground. The new value will take affect the next time
 * the IBeaconManager transitions between background and foreground mode.  To have it take effect
 * as soon as the next scan cycle starts, call setScanPeriods()
 * @param p
 */
public void setBackgroundScanPeriod(long p) {
    backgroundScanPeriod = p;
}
```

**Comment by rnevet** [comment]
My suggestion is changing the setScanPeriods to updateScanPeriods (to use a different terminology then the other set functions) and document it something like this:

```
/**
 * Updates an already running scan with scanPeriod/betweenScanPeriod according to Background/Foreground state.
 * Change will take effect on next scan cycle or pause.
 * @throws RemoteException - If the IBeaconManager is not bound to the service.
 */
    public void updateScanPeriods() throws RemoteException {
```

And this is my suggestion for the other set functions.

```
    /**
     * Sets the duration in milliseconds of each Bluetooth LE scan cycle to look for iBeacons.
     * This function is used to setup the period before starting a scan or switching between background/foreground.
     * To have it effect on an already running scan (when the next cycle start), call {@link #setScanPeriods}
     * @param p
     */
    public void setForegroundScanPeriod(long p) {
```

**Comment by davidgyoung** [comment]
Changed as described in 49d11ad49e10a5224bd7131055add744f3b1e53a
