### ISSUE TITLE
Gives NullPointerException in IBeaconManager checkAvailability() method

### ISSUE THREAD

**Issue by Mritunjaysingh** [RadiusNetworks/android-ibeacon-service#18]
I am developing one application with Ibeacons in android, I am facing an issue with verifying bluetooth low energy is available on device or not. For that, I used method of IbeaconManager class "checkAvailability()". But whenever I call this method, it instantly gives me exception for NullPointer, I checked that my IBeaconManager object is not null. but not sure, where the error is. 

Can you help me to resolve this bug or I may be doing anything wrong in the flow?

**Comment by davidgyoung** [comment]
Hi, @Mritunjaysingh.  Can you please try putting the lines below before your call to checkAvailability(), and let me know the log lines you see in LogCat?

Thanks,
David

```
    Log.d(TAG, "appContext is "+this.getApplicationContext());
    Log.d(TAG, "packageManager is "+this.getApplicationContext().getPackageManager());
    Log.d(TAG, "hasBluetoothLE is "+this.getApplicationContext().getPackageManager().hasSystemFeature(android.content.pm.PackageManager.FEATURE_BLUETOOTH_LE));
    Log.d(TAG, "bluetoothManager is "+this.getApplicationContext().getSystemService(Context.BLUETOOTH_SERVICE) );
    Log.d(TAG, "bluetoothAdapter is "+((android.bluetooth.BluetoothManager) this.getApplicationContext().getSystemService(Context.BLUETOOTH_SERVICE)).getAdapter() );
    Log.d(TAG, "enabled is "+((android.bluetooth.BluetoothManager) this.getApplicationContext().getSystemService(Context.BLUETOOTH_SERVICE)).getAdapter().isEnabled() );
```

**Comment by davidgyoung** [comment]
Hi, @Mritunjaysingh.  I cannot reproduce this issue, so I am closing this for now.  If you are still seeing this, and can put the log lines in your app as I have proposed above, please reopen the issue with the requested info.

**Comment by billmote** [comment]
I put those lines ahead of checkAvailability() and I am getting an NPE.  Here is the output:

05-19 09:22:29.872  29830-29830/com.example.helloworld.debug D/MainActivity﹕ appContext is com.example.helloworld.HelloWorldApplication@1221a945
05-19 09:22:29.872  29830-29830/com.example.helloworld.debug D/MainActivity﹕ packageManager is android.app.ApplicationPackageManager@5369b49
05-19 09:22:29.873  29830-29830/com.example.helloworld.debug D/MainActivity﹕ hasBluetoothLE is true
05-19 09:22:29.877  29830-29830/com.example.helloworld.debug D/MainActivity﹕ bluetoothManager is android.bluetooth.BluetoothManager@3f068c4e
05-19 09:22:29.877  29830-29830/com.example.helloworld.debug D/MainActivity﹕ bluetoothAdapter is android.bluetooth.BluetoothAdapter@26ddb16f
05-19 09:22:29.877  29830-29830/com.example.helloworld.debug D/MainActivity﹕ enabled is false
