### ISSUE TITLE
How to turn Android device into an iBeacon?

### ISSUE THREAD

**Issue by kramer65** [RadiusNetworks/android-ibeacon-service#19]
I'm after turning my Android device into an iBeacon, and I hoped to use your library for this. Unfortunately I just read [this page](http://developer.radiusnetworks.com/ibeacon/android/) on which it says:

> Unfortunately, it is not possible to make an iBeacon out of an Android device, because the Android Bluetooth LE APIs do not support the peripheral mode needed to send advertisement packets like in iBeacon.

Is there absolutely no way, also not by other libraries, to turn an Android device into an iBeacon?

**Comment by davidgyoung** [comment]
Sorry to deliver bad news.  I wrote a long explanation of why it is not possible in the blog post below.  The bottom line is that operating system changes are required to make this happen.

http://developer.radiusnetworks.com/2013/12/15/why-android-devices-cant-act-as-ibeacons.html

**Comment by kramer65** [comment]
Thanks for the quick reply. Unfortunate to hear this though. I had a read through your blog post, which initially made me think; "_yeah, maybe the Samsung lib works!!_", but unfortunately.

At least I also added my name to the feature request. We'll see what happens!
