### ISSUE TITLE
Power off android device and on again

### ISSUE THREAD

**Issue by Nedvedyy** [RadiusNetworks/android-ibeacon-service#25]
Hi,

If I power off the android device and power on again, will the previous running beacon service still be there? or I have to run any app with radius android SDK again?

Thanks
Nedved

**Comment by davidgyoung** [comment]
Nedved,

There are two different variants of the Android iBeacon Library:  the open source variant, and the Pro variant.  You can see the differences here:  http://developer.radiusnetworks.com/ibeacon/android/pro/download.html

The Pro Android iBeacon Library will automatically look for iBeacons when the mobile device starts up and optionally launch an app Activity or send a Notification when an iBeacon is detected.  See details here:  http://developer.radiusnetworks.com/ibeacon/android/pro/background_launching.html

The open source Android iBeacon Library does not contain code that does this automatically.  The service must be started by your app for iBeacon detection to happen, and starting it from an Activity or Application class requires your app to be manually launched by the user after boot.

Thanks,
David

**Comment by Nedvedyy** [comment]
Hi David,

Thanks for the explanation.

In terms of user experiences, iOS and Android are different right?

iOS: ibeacon notification to bring up the app will appear on screen only when you are not using the iOS7 app switcher to kill an app prior to IOS7.1. For iOS 7.1, notification will always be there?

Android:
1) if user runs the app with radius SDK (assuming for pro) once, the Ibeacon service will be started. In open source code version, it is a bound service, so it will be terminated when all consumers have gone.  For pro, shall I expect this ibeacon service always running ? Will it be terminated in any cases?

2) As what u have mentioned above, power on will always bring up the ibeacon service. Will the service notify its consumers (activities) which have not called unbind() before the phone turned off?

3) If I run the app with pro SDK once and ibeacon service runs infinitely. I click the back button which kills the activity (which is different from clicking on HOME button case, where it is really to bring the activity to background). Will this particular activity still be notified when the continuously running ibeacon service detects the right beacon? If yes, is it what user wants?

4) If I turn off the bluetooth when ibeacon service is running, should ibeacon service stop? And if bluetooth is on again, will the ibeacon service be started automatically? 

I have read your sharing of the expected monitoring and ranging behaviours for iOS in another thread, just a bit curious how does it look like for Android, which are more complicated with more scenarios?

regards
Nedved

**Comment by davidgyoung** [comment]
Answers inline below.
