### ISSUE TITLE
IBeaconManager.checkAvailability() seems inconsistent. 

### ISSUE THREAD

**Issue by pookzilla** [RadiusNetworks/android-ibeacon-service#27]
The IBeaconManager.checkAvailability() method does not seem to be consistent with its documentation. In the event that that OS build is insufficient false is returned rather than throwing a BLE exception would be indicated. As implemented this method can't be used to reliably craft UI based on the availability of BLE because on inadequate OS builds the result can't be distinguished from BLE being temporarily unavailable.

**Comment by davidgyoung** [comment]
Great point!

I have changed this to throw a BleNotAvailableException in ad42c9e.  

This will be rolled into the next binary release.

**Comment by pookzilla** [comment]
Thanks!
