### ISSUE TITLE
ConcurrentModificationException at IbeaconData

### ISSUE THREAD

**Issue by Sfavilla** [RadiusNetworks/android-ibeacon-service#29]
Hi, when the service runs for awhile, sometimes I get this Exception, I have 0.7.5 version

```
  E/AndroidRuntime(17077): FATAL EXCEPTION: main
  E/AndroidRuntime(17077): java.util.ConcurrentModificationException
  E/AndroidRuntime(17077): at java.util.HashMap$HashIterator.nextEntry(HashMap.java:806)
  E/AndroidRuntime(17077): at java.util.HashMap$KeyIterator.next(HashMap.java:833)
 E/AndroidRuntime(17077):   at com.radiusnetworks.ibeacon.service.IBeaconData.fromIBeacons(IBeaconData.java:43)
 E/AndroidRuntime(17077):   at com.radiusnetworks.ibeacon.service.RangingData.<init>(RangingData.java:42)
 E/AndroidRuntime(17077):   at com.radiusnetworks.ibeacon.service.IBeaconService.processRangeData(IBeaconService.java:466)
E/AndroidRuntime(17077):    at com.radiusnetworks.ibeacon.service.IBeaconService.finishScanCycle(IBeaconService.java:402)
E/AndroidRuntime(17077):    at com.radiusnetworks.ibeacon.service.IBeaconService.scheduleScanStop(IBeaconService.java:388)
E/AndroidRuntime(17077):    at com.radiusnetworks.ibeacon.service.IBeaconService.access$2(IBeaconService.java:375)
E/AndroidRuntime(17077):    at com.radiusnetworks.ibeacon.service.IBeaconService$3.run(IBeaconService.java:384)
E/AndroidRuntime(17077):    at android.os.Handler.handleCallback(Handler.java:730)
E/AndroidRuntime(17077):    at android.os.Handler.dispatchMessage(Handler.java:92)
E/AndroidRuntime(17077):    at android.os.Looper.loop(Looper.java:176)
E/AndroidRuntime(17077):    at android.app.ActivityThread.main(ActivityThread.java:5419)
E/AndroidRuntime(17077):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(17077):    at java.lang.reflect.Method.invoke(Method.java:525)
E/AndroidRuntime(17077):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
E/AndroidRuntime(17077):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
```

   E/AndroidRuntime(17077):     at dalvik.system.NativeStart.main(Native Method)

**Comment by ituuri** [comment]
getting the same thing here in my code, usually it takes about 5 minutes of running for it to occur, but sometimes quicker, not sure what the issue is yet, but if you find a solution please post it up..

**Comment by ituuri** [comment]
In my case I'm using an implementation of RangeNotifier from their library, within my code I'm implementing the method "public void didRangeBeaconsInRegion(Collection<IBeacon> iBeacons, Region region)"… in the hopes to avoid this above error I'm doing this at line 1 of that method:

//Copy the collection to avoid ConcurrentModificationException..
List<IBeacon> beacons = new ArrayList<IBeacon>(iBeacons);

..in other words i immediately copy the collection before operating on it, hopefully this will cure the issue for me..

**Comment by ituuri** [comment]
nope didn't fix it…error still occurs

**Comment by davidgyoung** [comment]
@iturri, can you post a stack trace?

**Comment by ituuri** [comment]
yeah, same as original commenters stack, but will repo it in a few moments here and post the stack..

**Comment by davidgyoung** [comment]
It sounds like you have some kind of setup that can reproduce this quickly.
 Any chance you have code you can share?  If I can reproduce it reliably,
I'm sure I can give you a quick fix.

**Comment by ituuri** [comment]
basically the pattern is like this, i have a service such as:

public class BeaconService extends Service implements IBeaconConsumer {
  …
  ..iBeaconManager.bind(this);
  …

  @Override
    public void onIBeaconServiceConnect() {
        Log.i(TAG, "Got beacon service connect..");

```
    if (beaconRangeNotifier == null) {
        beaconRangeNotifier = new BeaconRangeNotifier(getApplicationContext(), this);

        iBeaconManager.setRangeNotifier(beaconRangeNotifier);

        try {
            iBeaconManager.startRangingBeaconsInRegion(new Region("myMonitoringUniqueId", null, null, null));
        } catch (RemoteException e) {
            Log.i(TAG, "Got a RemoteException:" + e.getMessage());
        }
    } else
        Log.d(TAG, "IBeacon service reconnected but range notifier was already set");
}
```

  …
}

and BeaconRangeNotifier relevant code is:

public class BeaconRangeNotifier implements RangeNotifier {
  …
@Override
    public void didRangeBeaconsInRegion(Collection<IBeacon> iBeacons, Region region) {
        Log.d(TAG, "BeaconRangeNotifier didRangeBeaconsinRegion, this object:" + this);

```
    //Copy the collection to avoid ConcurrentModificationException..
    List<IBeacon> beacons = new ArrayList<IBeacon>(iBeacons);

   …then iterate over beacons collection copy and send out broadcast messages to receivers housed in activities..
```

}
  …
}

after some time of running the stack trace that appears in the first post above occurs within the iBeacons library code, i have verified i have a singular instance of the service and notifier code and that I'm not rebinding the iBeaconManger unless the service was destroyed and restarted, also note that this error occurs in a single lifetime of the service, no destroy or rebinding involved, all things exist once and bind once, let them sit for a while and eventually it breaks per the above commenters stack trace..

**Comment by ituuri** [comment]
ok, just got the error again, this time it took about 30 minutes of running before it repo'd:

04-16 12:03:52.434    3702-3702/com.mystuff.beacon E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.mystuff.beacon, PID: 3702
    java.util.ConcurrentModificationException
            at java.util.HashMap$HashIterator.nextEntry(HashMap.java:806)
            at java.util.HashMap$KeyIterator.next(HashMap.java:833)
            at com.radiusnetworks.ibeacon.service.IBeaconData.fromIBeacons(IBeaconData.java:43)
            at com.radiusnetworks.ibeacon.service.RangingData.<init>(RangingData.java:42)
            at com.radiusnetworks.ibeacon.service.IBeaconService.processRangeData(IBeaconService.java:488)
            at com.radiusnetworks.ibeacon.service.IBeaconService.finishScanCycle(IBeaconService.java:418)
            at com.radiusnetworks.ibeacon.service.IBeaconService.scheduleScanStop(IBeaconService.java:399)
            at com.radiusnetworks.ibeacon.service.IBeaconService.access$100(IBeaconService.java:61)
            at com.radiusnetworks.ibeacon.service.IBeaconService$2.run(IBeaconService.java:395)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5476)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by davidgyoung** [comment]
@iturri, I am having trouble reproducing.  Will you do the following for me?
1. Somewhere in your code, set 

IBeaconManager.LOG_DEBUG = true;
1. Run your code again until you get the stack trace as above.
2. Send me the logcat lines for two seconds before the stack trace occurs (it may be big and you can send it to me privately at david@radiusnetworks.com if you prefer).  I am particularly interested in lines that look like this:

Calling ranging callback with X iBeacons

Thanks,
David

**Comment by davidgyoung** [comment]
@iturri, I suspect this problem may have the same root cause of the issue #30 below.  While I cannot reproduce the stack trace of this issue, the fix for issue #30 will fix this issue as well if it is indeed the same root cause.  If you have a chance, please try the new build:

http://s3.amazonaws.com/android-ibeacon-library.radiusnetworks.com/AndroidIBeaconLibrary-0.7.6.1.aar

http://s3.amazonaws.com/android-ibeacon-library.radiusnetworks.com/AndroidIBeaconLibrary-0.7.6.1.tar.gz

**Comment by keremgocen** [comment]
I have the same problem. I believe the issue can be reproduced with too many beacon devices around. Here is a stack trace, it's quite similar to the others.

java.util.ConcurrentModificationException
java.util.HashMap$HashIterator.nextEntry(HashMap.java:806)
java.util.HashMap$KeyIterator.next(HashMap.java:833)
com.radiusnetworks.ibeacon.service.IBeaconData.fromIBeacons(IBeaconData.java:43)
com.radiusnetworks.ibeacon.service.RangingData.<init>(RangingData.java:42)
com.radiusnetworks.ibeacon.service.IBeaconService.processRangeData(IBeaconService.java:466)
com.radiusnetworks.ibeacon.service.IBeaconService.finishScanCycle(IBeaconService.java:402)
com.radiusnetworks.ibeacon.service.IBeaconService.scheduleScanStopIBeaconService.java:388)

**Comment by keremgocen** [comment]
@ituuri and @Sfavilla please see #36.

**Comment by Sfavilla** [comment]
Thanks I'll try the code with the changes

**Comment by keremgocen** [comment]
I am running the application with modifications in #36 since Friday and I haven't seen the error so far. Please let me know about the results.
