### ISSUE TITLE
Apparent multiple callbacks after repetitive stop/start cycles

### ISSUE THREAD

**Issue by jamesfalkner** [RadiusNetworks/android-ibeacon-service#30]
My app periodically fetches a new list of regions to monitor from my server, every 10 minutes or so (in case region configuration has been changed by the admin, which is not likely, but possible, so that usually the same set of regions is returned).

What I do when I get a new list of regions is to first stop ranging and monitoring everything currently monitored or ranged (exception handling removed for brevity):

```
for (Region r : iBeaconManager.getMonitoredRegions()) {
    iBeaconManager.stopMonitoringBeaconsInRegion(r);
}
for (Region r : iBeaconManager.getRangedRegions()) {
    iBeaconManager.stopRangingBeaconsInRegion(r);
}
```

And then I start monitoring the new set of regions with `iBeaconManager.startMonitoringBeaconsInRegion(region)` (my consumer automatically begins ranging a region when it is entered, via its monitoring callback)

What I am noticing is that after several cycles of stopping/starting monitoring the same set of regions, there appear to be in the log many instances of something generating LE scans. I see big blocks of debug like:

```
D/IBeaconService(29603): Waiting to start next bluetooth scan for another 1394 milliseconds
D/IBeaconService(29603): Waiting to start next bluetooth scan for another 1378 milliseconds
D/IBeaconService(29603): Waiting to start next bluetooth scan for another 1372 milliseconds
D/IBeaconService(29603): Waiting to start next bluetooth scan for another 1365 milliseconds
D/IBeaconService(29603): Waiting to start next bluetooth scan for another 1352 milliseconds
D/IBeaconService(29603): Waiting to start next bluetooth scan for another 1339 milliseconds
D/IBeaconService(29603): Waiting to start next bluetooth scan for another 1332 milliseconds
D/IBeaconService(29603): Waiting to start next bluetooth scan for another 1326 milliseconds
D/IBeaconService(29603): Waiting to start next bluetooth scan for another 1319 milliseconds
D/IBeaconService(29603): Waiting to start next bluetooth scan for another 1310 milliseconds
D/IBeaconService(29603): Waiting to start next bluetooth scan for another 1299 milliseconds
D/IBeaconService(29603): Waiting to start next bluetooth scan for another 1299 milliseconds
```

And other repetitive blocks such as

```
D/IBeaconIntentProcessor(29603): got ranging data
D/IBeaconIntentProcessor(29603): got an intent to process
D/RangingData(29603): parsing RangingData
D/RangingData(29603): parsing RangingData
D/IBeaconIntentProcessor(29603): got ranging data
D/IBeaconIntentProcessor(29603): got an intent to process
D/RangingData(29603): parsing RangingData
D/RangingData(29603): parsing RangingData
D/IBeaconIntentProcessor(29603): got ranging data
D/IBeaconIntentProcessor(29603): got an intent to process
D/RangingData(29603): parsing RangingData
D/RangingData(29603): parsing RangingData
D/IBeaconIntentProcessor(29603): got ranging data
....

```

I'm not sure if this is bad, because when multiple LE scans are initiated, all but the first notice the scan is already in progress, but I am concerned there are multiple callbacks from the service eating up memory and battery.

**Comment by jamesfalkner** [comment]
Also, this is with version 0.7.6 of the open source library on a Nexus 7.

**Comment by jamesfalkner** [comment]
Yeah, I pasted a large chunk of adb output (with timestamps) here:

https://gist.github.com/jamesfalkner/b777e3145f4e91b1020c

You can see in there where I am cycling monitoring/not monitoring and several big chunks where what appear to be multiple threads trying to start/stop scanning and reporting results.

**Comment by davidgyoung** [comment]
I believe I have a fix as of 1a2aa13d06d9b01286682352fbe1afb3e02dbe23

James, I have rolled a new build at the links below.  Please try it when you have a chance and let me know if it resolves your issue.

Thanks,
David

http://s3.amazonaws.com/android-ibeacon-library.radiusnetworks.com/AndroidIBeaconLibrary-0.7.6.1.aar

http://s3.amazonaws.com/android-ibeacon-library.radiusnetworks.com/AndroidIBeaconLibrary-0.7.6.1.tar.gz

**Comment by jamesfalkner** [comment]
Hey David, just wanted to thank you for taking the time to check into and fix this.. Using 0.7.6.1 I no longer see the tons of scanLE attempts, however after a few cycles of starting/stopping monitoring and ranging, there still seems to be something lingering. Just before I call `iBeaconManager.stopMonitoringBeaconsInRegion(r)` in a loop (to stop monitoring all regions that the iBeaconManager thinks it is managing), I printed out the number of regions returned from `iBeaconManager.getMonitoredRegions().size()` - this size seems to be constantly going up (after several cycles of turning on/off monitoring, the size of `iBeaconManager.getMonitoredRegions()` is currently up to 66 and increasing).

What's odd is that even if I back out of and fully close my app, when I re-launch it, the number of regions reported by `iBeaconManager.getMonitoredRegions()` is huge (now up to 97), even before I turn on monitoring for any regions. Even if I exit app, toggle bluetooth off and back on, and restart app, it still thinks it is monitoring 100+ regions!

**Comment by davidgyoung** [comment]
OK, glad I fixed ONE problem :)  Do you mind opening a new issue for this since it is a little different?  I'll investigate that separately and close this one.

**Comment by jamesfalkner** [comment]
Haha, sure, no problem. I'll include some more debugging info in the next one :) Thanks again for your responsiveness!
