### ISSUE TITLE
Logging at INFO level is annoying

### ISSUE THREAD

**Issue by a613** [RadiusNetworks/android-ibeacon-service#33]
Some logging statements produced by this library are at the INFO level, which is pretty intrusive.

Specifically I'm looking at the line in [`IBeaconService.processIBeaconFromScan()`](https://github.com/RadiusNetworks/android-ibeacon-service/blob/master/src/main/java/com/radiusnetworks/ibeacon/service/IBeaconService.java#L555).

**Comment by davidgyoung** [comment]
Good point.  I will demote that one to debug level (which will be not logged at all by default).  If you have other proposed candidates for this treatment, please say so.

**Comment by davidgyoung** [comment]
changed as described in 28c59f5
