### ISSUE TITLE
Is this library compatible with Google Glass XE16.x?

### ISSUE THREAD

**Issue by thecoleorton** [RadiusNetworks/android-ibeacon-service#34]
Is this library compatible with Google Glass XE16.x? Has anyone tried? Any tips?

Thanks in advance.

**Comment by davidgyoung** [comment]
Since the upgrade of Google Glass to Android 4.4, yes, this should be compatible.  I have not tried, so perhaps you can give it a shot and let us know!

**Comment by thecoleorton** [comment]
I'm using it right now on Glass XE16.2 - so far so good!

If only I could prevent Glass from going to sleep after about 15 seconds or so :D

**Comment by powerje** [comment]
@thecoleorton this I/O video from last year has instructions for changing that setting:
https://developers.google.com/events/io/sessions/332704837

Basically you modify Glass to run like a normal Android device and use a bluetooth mouse to adjust your settings. I haven't tried it with XE16.x myself though - I was one of the unlucky ones with a bootloop issue :(

**Comment by thecoleorton** [comment]
@powerje Ah, yes, I've seen that video as well... There's got to be a way to do it programmatically though as while playing their game demos the device doesn't go to sleep. 

This is my first Android project - which just happens to be for Glass - so, I've got quite a bit of catching up to do...

**Comment by powerje** [comment]
Oh, I imagine something like: 

getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);

in your Activity should do that.

**Comment by thecoleorton** [comment]
Ah, yes, I found a similar layout value in the Charades example, see: https://github.com/googleglass/gdk-charades-sample/blob/master/res/layout/activity_start_game.xml#L22
