### ISSUE TITLE
RSSI is negative with USB Radius beacon

### ISSUE THREAD

**Issue by Nedvedyy** [RadiusNetworks/android-ibeacon-service#35]
Hi,

I am using USB radius beacon and getting RSSI = -64 on iOS7 phone. May I know it is normal? On https://developer.apple.com/library/ios/documentation/CoreLocation/Reference/CLBeacon_class/Reference/Reference.html#//apple_ref/occ/instp/CLBeacon/rssi , it says accuracy can be negative, but not RSSI. Is it a hardware fault?

Regards
Ned

**Comment by Sfavilla** [comment]
Hi, I have used iBeacon for awhile and RSSI is always negative. It is the received signal strength in db.And the value you are getting is normal.

**Comment by davidgyoung** [comment]
Yes,  a negative value is typical  to be expected.  A value of 0 would be an extremely strong signal, a value of -100 would be a weak signal, and a value of -64 would be typical.
