### ISSUE TITLE
Bluetooth crash recovery infinite loop on Galaxy S3

### ISSUE THREAD

**Issue by kdaker** [RadiusNetworks/android-ibeacon-service#38]
The crash recovery isn't working properly when testing on a Galaxy S3. When it crashes, the app tries to scan, it keeps logging `Skipping scan because crash recovery is in progress` infinitely. Quitting the app and launching it again fixes it. 

This doesnt happen when testing on a Nexus 4.

![screen shot 2014-05-14 at 5 23 33 pm](https://cloud.githubusercontent.com/assets/905997/2979198/5e7433ac-dbc8-11e3-8c27-c579783a4083.png)

**Comment by nickdecooman** [comment]
This issue also occurs on a Nexus 7.

Prior to the infinite loop, this output is shown:

2073-2073/mobi.beacons.test W/BluetoothCrashResolver﹕ BluetoothService crash detected
2073-2073/mobi.beacons.test W/BluetoothCrashResolver﹕ Recovery attempt started
2073-2073/mobi.beacons.test W/BluetoothCrashResolver﹕ BluetoothAdapter.ACTION_DISCOVERY_STARTED never received.  Recovery may fail.
2073-2073/mobi.beacons.test W/BluetoothCrashResolver﹕ BluetoothService crash detected

**Comment by bklarson** [comment]
I also see 'BluetoothAdapter.ACTION_DISCOVERY_STARTED never received. Recovery may fail.' on a GS3, and haven't had any luck getting bast the 'Bluetooth share has stopped' bug short of a factory reset.

**Comment by jessolo** [comment]
I am getting this error on Galaxy Note 3 and beacon detection is not starting. This is the error I am getting. What is the issue with this? I am using AltBeacon version 2.1. Has this been fixed in later releases?

09-14 15:44:21.533    4488-4488/com.cvs.launchers.cvs W/BeaconService﹕ Skipping scan because crash recovery is in progress.

**Comment by davidgyoung** [comment]
Moving this to new repo:  

https://github.com/AltBeacon/android-beacon-library/issues/282

**Comment by davidgyoung** [comment]
@jessolo, please see the new issue I created for this.  I have a question for you there.
