### ISSUE TITLE
Unable to start service Intent { cmp=myPackageName/com.radiusnetworks.ibeacon.service.IBeaconService } U=0: not found

### ISSUE THREAD

**Issue by hejianboo** [RadiusNetworks/android-ibeacon-service#39]

**Comment by craniumrat** [comment]
Add the following line in your project.properties file:
manifestmerger.enabled=true

After adding it and compiling, the bin/Android.xml will now have a reference to the IBeaconService service.

**Comment by hejianboo** [comment]
Thanks! It works!
