### ISSUE TITLE
NoclassDefFoundError when implements BootstrapNotifier for the Background mode. 

### ISSUE THREAD

**Issue by Alessqc** [RadiusNetworks/android-ibeacon-service#42]
I have been trying to make the Radius Network Background mode work, with no success at this moment. I even copied the code from the following link  : http://developer.radiusnetworks.com/ibeacon/android/samples.html . To see if it could work..  I tried to extend my class as a intentService, Application and Service none of those work.. My class normally work, but as soon as I implement the BootstrapNotifier I am having a No calss definition Error and my App crashes. 

What I am trying to do is when I click on a button, the background functionality starts monitoring. 

Here is my code for the background mode: 

import android.app.IntentService;
import android.content.Intent;
import android.util.Log;

import com.radiusnetworks.ibeacon.Region;
import com.radiusnetworks.proximity.ibeacon.startup.BootstrapNotifier;
import com.radiusnetworks.proximity.ibeacon.startup.RegionBootstrap;

public class BackgroundService extends IntentService implements BootstrapNotifier {

```
   private static final String TAG = "BackgroundService";

public BackgroundService() {
    super("BackgroundService");
    // TODO Auto-generated constructor stub
}

@Override
public int onStartCommand(Intent intent, int flags, int startId){
    Log.d(TAG, "service starting");
    Region region = new Region("com.cubic.blebeacon.BackgroundApplication",
            "A90BABD0-2542-4001-A8D9-92EE6E7CF6E7", null, null);
    new RegionBootstrap(this, region);

    return super.onStartCommand(intent,flags,startId);
}

@Override
public void onDestroy() {
    Log.d(TAG, "Service done");
}

@Override
public void didEnterRegion(Region arg0) {
    Log.d(TAG, "did enter region.");
    Intent intent = new Intent(this, MainActivity.class);
    intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);

    // Important:  make sure to add android:launchMode="singleInstance" in the manifest
    // to keep multiple copies of this activity from getting created if the user has
    // already manually launched the app.
    this.startActivity(intent);
}
@Override
public void didExitRegion(Region arg0) {
    Log.d(TAG, "exited region");
}
@Override
public void didDetermineStateForRegion(int arg0, Region arg1) {
    Log.d(TAG, "Did determine State for region");
}

@Override
protected void onHandleIntent(Intent intent) {
    // TODO Auto-generated method stub

}
```

}

Note that I am new in the android application development, and that I did a lot of research before posting this issue..

**Comment by davidgyoung** [comment]
First, I should note that this question is about a feature that is only available in the Pro Android iBeacon Library, but this issue is opened under the repository for the open source version of the Android iBeacon Library.  If you are using the open source library, then the issue is that this feature requires the pro library.

If you are using the pro library, please send a support question to support@radiusnetworks.com, and include 1. The version number of the library you are using.  2. A complete stack trace from LogCat for the NoclassDefFoundError
