### ISSUE TITLE
[Feature] Add advertising support

### ISSUE THREAD

**Issue by schickling** [RadiusNetworks/android-ibeacon-service#43]
It would be awesome (and more complete) if this project would enable android users to also emit iBeacon data, in other words: enable advertising.

This would include the methods `startAdvertising`, `stopAdvertising` and the property `isAdvertising`. More info can be found here: https://developer.apple.com/library/ios/documentation/CoreBluetooth/Reference/CBPeripheralManager_Class/Reference/CBPeripheralManager.html#//apple_ref/occ/instp/CBPeripheralManager/isAdvertising

Keep up the great work guys!

**Comment by cmelchior** [comment]
Android doesn't support BLE advertisement in the current API's, so unfortunately that isn't possible. We can only wait for Google to add that support. There is a request in the Google Bugtracker here: https://code.google.com/p/android/issues/detail?id=59693

**Comment by davidgyoung** [comment]
Agreed.  I am anxiously awaiting Android 4.5 to see if support is included.  If it is, this library will add the feature.

**Comment by schickling** [comment]
Thanks for these information!
