### ISSUE TITLE
Not able to integrate the beacon library with existing project

### ISSUE THREAD

**Issue by ashishkr01** [RadiusNetworks/android-ibeacon-service#46]
I am not able to integrate the beacon library into my current android project as I am not getting the base class. 

I am getting errors in overridden methods of child classes for methods defined in base class 'Activity' which has been extended by child classes. 

Please provide some help urgently.

Regards 
Ashish Kumar

**Comment by davidgyoung** [comment]
Hi, Ashish.  If you need help with the project setup on the free open source library, can you please post your question on StackOverflow.com with the tag ibeacon-android?  This is a better way to get free community support.  Issues in this forum are reserved for internal implementations of the library.

If you take this route, please tell us whether you are using Android Studio or Eclipse, and post your code that is giving you problems along with details of the errors you are getting (and maybe screenshots of the errors if they are only visible graphically in the IDE.)

Thanks,
David
