### ISSUE TITLE
Not able to integrate the beacon library with existing project

### ISSUE THREAD

**Issue by ashishkr01** [RadiusNetworks/android-ibeacon-service#47]
![issue1](https://cloud.githubusercontent.com/assets/7861330/3303245/3477ee7e-f63d-11e3-92ca-0569ed7149e3.png)
![issue2](https://cloud.githubusercontent.com/assets/7861330/3303244/345526f0-f63d-11e3-809e-3d08f085256b.png

**Comment by ashishkr01** [comment]
I was trying to integrate proximity library into brightdoorbuzz

**Comment by davidgyoung** [comment]
For free assistance with project-specific uses of the Android iBeacon Library, please create a new question on StackOverflow.com with the tag ibeacon-android:  http://stackoverflow.com/a/21553009/1461050

If you have a paid subscription to the Pro Android iBeacon Library or Proximity Kit, you can also open a support ticket at support@radiusnetworks.com
