### ISSUE TITLE
Cordova Plugin tweak

### ISSUE THREAD

**Issue by mrtree1** [RadiusNetworks/android-ibeacon-service#50]
I've used a fork of this project to build the Android side of a Cordova/PhoneGap plugin. As I included the code in the project rather than include a jar I had one minor edit to make which is not essential to the project at all to remove the Build version log comment being generated. I'm just wondering if this can be altered in the original code to make it easier for me and maybe others to keep up to date with this project?

Here's my tweak: https://github.com/mrtree1/android-ibeacon-service/commit/bf86d2352cdee194d9255bf1f32c12261e9be772 

Here's the plugin: https://github.com/petermetz/cordova-plugin-ibeacon

**Comment by schickling** [comment]
@mrtree1 to save you some time: https://github.com/mobilion/cordova-ibeacon-plugin/

**Comment by mrtree1** [comment]
I'm not sure what your saying. There's quite a few other ibeacon plugins and the one by PeterMetz has the most robust architecture I've seen. I could just add the JAR certainly, I was just raising a point about a small change to make things easier to embed if anyone wants to use the code that way.
