### ISSUE TITLE
Note From CEO Page is Down

### ISSUE THREAD

**Issue by AaronRietschlin** [RadiusNetworks/android-ibeacon-service#51]
I know this repo has been removed but I am hoping you may be able to still help me out. 

First thing, the Note from the CEO page is down and reporting a 404. 

Second, all of the beacon functionality in my apps have suddenly stopped working. It seems unlikely, but could this have anything to do with this repo being removed (note: I am using the local AAR via gradle). Again, I doubt this is the reason, but nothing has changed in the code for my apps that were previously monitoring correctly and they have suddenly stopped.

**Comment by MegatronCupcakes** [comment]
I would also like to read the note from the CEO.  

I'm on the verge of releasing an app that used this and need to know if the licensing terms have changed.  All references to the Open Source Android iBeacon package have been removed from the Radius Networks website.

**Comment by davidgyoung** [comment]
Sorry about this.  Please send an email to support@radiusnetworks.com for more info.  To answer@nemisis, there is no reason that the functionality in your existing apps should stop working, so it must be unrelated.
