### ISSUE TITLE
is it not possible to bind a service on BeaconManager.bind(myService)  ???

### ISSUE THREAD

**Issue by Excellsior** [RadiusNetworks/android-ibeacon-service#53]
hello,

when i bind an Activity implements BeaconConsumer  (for example myActivity) with: 
BeaconManager.bind(myActivity) --> it works fine !!!

when i try to bind a  Service implements BeaconConsumer (for Example myService) with
BeaconManager.bind(myService) the app crashes with a NullPointerException

does BeaconManager.bind() not work with Services that implements Beaconconsumer, only with Activities that implements the BeaconConsumer ??

the docs says:

"public interface BeaconConsumer
An interface for an Android Activity or Service that wants to interact with beacons. ... "

 thanks, timo

**Comment by davidgyoung** [comment]
Timo, yes the BeaconManager is designed to work with Services as well as Activities, and others have reported this working fine.  If you susoect this is a problem with the library, please include the stack trace of your crash.

**Comment by Excellsior** [comment]
hello,

thx for your quick answer. i´ve written a second new project with 
minimal code and it survived the codeline with 
BeaconManager.bind(myService).
then i restarted my old project and it worked there too. don´t know what 
happened but i´m happy that it is working now.
my fault, sorry.

regards timo

Am 16.10.2014 14:53, schrieb David G. Young:
