### ISSUE TITLE
How to calculate distance/accuracy when we need rapid updates from the beacons

### ISSUE THREAD

**Issue by rajtrivedi88** [RadiusNetworks/android-ibeacon-service#54]
I need rapid updates to calculate the distance of device from beacon.I am using RunningAverageRssiFilter for stationary case.Please suggest some implementation for rapid updates scenario.Also,is ARMA filter useful enough for rapid updates?

**Comment by davidgyoung** [comment]
@rajtrivedi88, there is documentation about this feature here:  http://altbeacon.github.io/android-beacon-library/distance_vs_time.html

Please note that this forum is reserved for feature requests and for reports of bugs with the library itself.  If you would like assistance on using the library for specific applications, please open a question on StackOverflow.com.
