### ISSUE TITLE
Provide fields for the store number, store name, zip code and addresses in order data

### ISSUE THREAD

**Issue by davidhelms** [RadiusNetworks/android-ibeacon-service#57]

**Comment by willshepherdson** [comment]
Any reason why this is in android-ibeacon-service? I assume it's inadvertent -- should I close and re-create?

**Comment by willshepherdson** [comment]
Updated planner to include Address, City, State, and ZIP. Need to review with Joe and see if he pulls any other fields.

**Comment by willshepherdson** [comment]
Feedback from Joe: Add download button to the custom page - as well as in the database - somehow have a separate field for the store # and zip code.

i know its now in the ready to bill report but think that is more a report filter vs the raw data base.
