### ISSUE TITLE
iBeacon AD filter too strict

### ISSUE THREAD

**Issue by slackhappy** [RadiusNetworks/android-ibeacon-service#6]
It looks like the advertisement filter was improved in https://github.com/RadiusNetworks/android-ibeacon-service/commit/d9c130ff36f39095773d99027172c55f0f781291, but it is still too strict compared to iOS.

I created custom advertisement that left out the AD Flags entirely, and iOS still ranged the beacon successfully.  I started with 1A FF 4C 00 02 15.  You might want to scan the first few bytes scanData[0] to scanData[4] for the beginning of the iBeacon AD entry.

**Comment by davidgyoung** [comment]
Thanks for this.  I'm not sure I understand the details of what you are saying.  The filter currently looks only for the sequence 4C 00 02 15.  That was the change in the revision you mention.  Are you saying some of these four bytes should not be part of the filter?

**Comment by slackhappy** [comment]
I'm saying that 4C could start at scanData[2] up to scanData[6]

my full advertisement started like:
scanData[0] == 0x1a
scanData[1] == 0xff
scanData[2] == 0x4c
scanData[3] == 0x00
scanData[4] == 0x02
scanData[5] == 0x15
//UUID
//Major
//Minor
//txPower

**Comment by davidgyoung** [comment]
Oh, I see.  Yes, you are correct -- I was able to verify this with another iBeacon that starts at byte 2.  I have pushed changes to master for this in  https://github.com/RadiusNetworks/android-ibeacon-service/commit/1e4f6aff05ebf046a030c199cf6322c6e1d5cd6b

**Comment by slackhappy** [comment]
Awesome! Thanks!
