### ISSUE TITLE
Nexus 7 2013 getting ANR when Bluetooth setting is off

### ISSUE THREAD

**Issue by bob-lee** [RadiusNetworks/android-ibeacon-service#7]
My app is ranging beacons ok in favorable conditions but if I turn Bluetooth off and start the app, then I got ANR. I could avoid this situation by checking isEnabled() on onCreate().

But still got ANR if I turn Bluetooth off in Setting while my app is ranging.

Logcat shows below every seconds, then my app eventually crashes with ANR:
E/BtGatt.GattService(1089): getService() - Service requested, but not available!

Do you think user activity is responsible to handle this or the library can do something to help this out?

Regards
Bob

**Comment by davidgyoung** [comment]
Hi, Bob.  Thanks for the report.  I have reproduced your problem -- I had not noticed that until now.  

I agree that the library should handle this more gracefully if possible.  I will have to look into whether the hang happens inside the bluetooth libraries or not to see if we can make something more graceful happen.

**Comment by davidgyoung** [comment]
Fixed in f14bd552700a888b9af757d7a25ed487f24a0a19.  The ANR can be avoided by checking to see if bluetooth is disabled before starting/stopping a scan.  This is available on master right now, and will go into the next binary release.  If you need a binary release sooner, please let me know.
