### ISSUE TITLE
Version 0.7.1 not available for download on the project website

### ISSUE THREAD

**Issue by IGZdavidgarcia** [RadiusNetworks/android-ibeacon-service#9]
Neither the .aar nor the .tar.gz appear to be uploaded on the links provided for the latest version:

![image](https://f.cloud.github.com/assets/2338951/1703763/b8afc314-60bb-11e3-8fc6-5d6c7ac95caa.png)

**Comment by davidgyoung** [comment]
Sorry about that -- incorrect permissions on Amazon.  I believe I have resolved this issue.  Please let me know if you still have trouble.

**Comment by IGZdavidgarcia** [comment]
Downloaded with no problem. Thanks!
